[package]
name = "macro-token-client"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "1.0"
quote = "1.0"


hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro_derive" }
